import Head from 'next/head';
import SideBar from '../src/components/SideBar';
import Channelbar from '../src/components/ChannelBar';
import ContentContainer from '../src/components/ContentContainer';

export default function Home() {
	return (
		<div className="home-container">
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
			<h3>hello therr</h3>
		</div>
	);
}
